name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Extract base version
        uses: sergeysova/jq-action@v2
        id: base-version
        with:
          cmd: jq --raw-output .version package.json
      - name: Determine version string
        uses: ./.github/actions/determine-version
        id: version
        with:
          base-version: ${{ steps.base-version.outputs.value }}
      - name: Report version
        run: |2
          echo "${{ steps.version.outputs.version }}"
      - name: Update package.json
        run: |2
            npm --no-git-tag-version version "${{ steps.version.outputs.version }}"
      - name: Add Checks
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Version
          output: |2
            {
              "summary": "Unique version string created",
              "text_description": "The version string for this build has been set to **${{ steps.version.outputs.version }}**"
            }
      - name: Install Dependencies
        run: npm ci
      - name: Build
        env:
          NODE_ENV: production
        run: npm run build
      - name: Clean Dev Dependencies
        run: |2
          rm -rf node_modules/
          npm ci --production
          mkdir -p node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: .

  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Install dev dependencies
        run: npm ci
      - name: Check Code
        run: npm run check

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
      - name: Install dev dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
